version: '3'
services:
  emqx:
    container_name: emqx
    image: emqx/emqx
    restart: unless-stopped
    ports:
      - 1883:1883
      - 18083:18083
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - 3000:3000
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    restart: always
